### PR TITLE
Easier translation option for the mod

### PR DESCRIPTION
**Pull request by Lonarix**
- I've made translating the mod easier by having translators upload a single file as a mod instead of their own `init.lua`, `Config.lua`, `UIText.lua`, `Stronger.lua` and `TurnOff.lua`, etc., a `Translation.lua` is now completely sufficient.

- Changing the preset names no longer makes the preset unusable. Displaynames only replace the actual name of the preset in the UI, not everywhere else.

- Translations are now compatible with newer UIText versions, if a new version of the mod is released and the translator has not finished translating it, the mod automatically reverts to the original language

- I tested on main-xl branch and extended to develop-xl branch (untested)

- The example of a `Translation.lua` is called `Translation_Blueprint.lua` and is a simple copy of the short `UIText.lua`

### CODE REVIEW

**Comment by gramern** [comment]
Hi, thanks for your contribution! 

Sure, I will check your changes and add them accordingly, but let me revise it first. The mod's code needs massive 'despaghettification' and optimizations as the main algorithm is finally developed and readable. I have already done some of that in my local repo. Tomorrow, I'll go through your changes, and I'll let you know my thoughts on those and we'll decide how to merge them.

**Comment by Lonarix** [comment]
Hi,

Of course, no problem, take your time and do what you already had in mind. Lua is not exactly my strength, so I'm sorry if it's not practically implemented. 

In itself, is not much changed, I have only added a few lines, biggest change is the `UIText.lua` and `Translation_Blueprint.lua`. To make it look more efficient, you could also simply omit the `Translation_Blueprint.lua` and upload it later as a single .lua for translation.

**Comment by gramern** [comment]
Adding an easy way to translate the mod along with a blueprint is a great idea. However, some of those changes tie preset files with other modules. This is in opposition to the original goal of the presets system: the possibility to independently load any presets as long as they follow their table blueprint and are placed in the Presets folder, while the mod takes care of the rest.

After these changes, each added preset also requires a hardcoded path to a localization table. This follows the current code structure of the mod but makes changes more tedious and adds an additional dependency to presets, which should remain as data carriers only.

Let me finish the code overhaul; I should publish commits this weekend. After that, adding a full-fledged localization system that avoids these issues while allows for loading multiple UI translations, also for descriptions of presets shipped with official mod releases, will be easy and I'll appreciate your contribution.

**Comment by Lonarix** [comment]
I hope I was able to accommodate you a little with my last commit, even if I think it's more like a drop in the ocean.

In any case, I'm very excited to see what else you do with the mod.

**Comment by gramern** [comment]
Hi, yep, it's better! But I have even another idea. In 4.9.0, I'll implement `ID` signatures for preset files. From then on, the mod will be listing and loading presets based on their identification signature. `ID` will be a random number from 100 to 999999 assigned randomly by an author of a preset. The pool is big to minimize the risk of the same signature being allocated twice by different presets. :) 0-99 is reserved for built-in ones.

I still need more time as I'm restructuring and rewriting the code, so I won't publish it today. But I sketched a simple scheme for 4.9.0:
[https://app.spline.design/file/e07020d8-0ec9-4bed-a713-2c521852fd52](https://app.spline.design/file/e07020d8-0ec9-4bed-a713-2c521852fd52)

The mod's new `Config.lua` module will be sending a list of presets' `ID`s loaded by the `Presets.lua` module and an `ID` of a currently selected preset to the new `Localization.lua`. The localization system will be updating the `UIText.lua` table based on a found `Translation.lua`. Then, the mod's UI can grab and show translated names and descriptions of presets assigned to a loaded list of preset `ID`s. If there's none for an ID in a selected/loaded translation, `Localization.lua` puts the default English name and description in the `UIText` table.

In the future, the localization system may be developed further: loading multiple translations from a separate folder, loading one based on the game's selected language, and so on.

I'm not holding you back: if you want, you can start writing a `Localization.lua` now, so it could become a more universal solution for other CET-based mods as well! All 4.9.0 needs from it, is the functionality described above.

**Comment by Lonarix** [comment]
Unfortunately, I don't know anything about `Lua` and `CET`. I can translate and add something, but that's no miracle, Lua is pretty easy to read.

I'm out of the question for more complex projects in Lua. I did try to look at `Localization.lua`, but unfortunately I hardly have any time during the week and since I only look at codes now and then as a little pastime or create smaller projects in typescript, this file would keep me busy for ages.

I was able to make a little progress, for example recognizing the user's language `Game.NameToString(Game.GetSettingsSystem():GetVar("/language", "OnScreen"):GetValue())`, but that's about it, because unfortunately I can't find the error when loading the corresponding translation file.

I suspect the error is somewhere in the section in which I replace the `UIText` key values ​​with the translation file Key values ​​or when loading the various files, even though I kinda converted this code from the presets.

In addition, embedding the file broke the UI for me, and here too I have no idea where the error came from.

If you still want to take a look at the file, I can send it to you in the next commit. I haven't integrated the ID of presets yet. I'll be happy to take another look at it tomorrow after work, but unfortunately I can't promise anything.

**Comment by gramern** [comment]
Hey, congratulations on the progress already - if you've found a way to get the game's current language, the rest should be easy. But I know this might be not the case with the current code. The reason UI is falling apart should be logged in the mod's log file (`FrameGenGhostinFix.log` in the mod's CET folder). CET's main folder also contains a few handy log files.

In this case, I would stop building the code based on 4.8.2 - the mod's current code grew organically, and I'm aware that adding and testing new features might be tedious. That's why there's the rework coming, and I don't want you to waste your time till 4.9.0-alpha1.

Most of the code is already revised and rewritten, but I need a break to get a fresh perspective before putting modules together again and refactoring. This is taking more time than I expected. I wouldn't hurry then.

For now, the mod is working, and your translation is too. Since one of the goals for 4.9.0 is to make adding new features and translations much easier, there'll be enough time to have a look into 4.9.0-alpha and prepare a new German localization before release for sure. :)

**Comment by Lonarix** [comment]
Well, I think I've done it. Unfortunately I haven't been able to test the IDs properly yet, as I don't yet know exactly how you want it, but I've finished and tested the `Localization.lua` (mostly, I couldn't test the preset IDs exactly, only with dummy tables)

It now looks different to what I had planned, but it works perfectly as far as I could test it.

`SetLanguage()`, `Localization.transalte()` and `Localization.updatePresets()` are always executed when the user opens the UI, so the language is always updated automatically and changing the language doesn't require reloading the mod.

`Localization.presetsList` is a list of all the preset names translated and `Localization.presetIDs` is a list of all the preset ids with the same key as it's name. Only updated when the UI is opened.

A Presets author, description and name can be found using `Localization.UIText.Presets.Info[presetID]`.

`Localization.lua` needs Config to return a `presetInfoStack` as I used `Config.presetInfoStack` to get the prests. It needs the following structure to work:
`{ PresetID = { name = "Preset's Name", description = "Preset's description", author = "Preset's author name" }, ... }`
so for **example**
`{ [90]= { name = "Default", description = "Default's description", author = "gramern" }, ... }`

I also didn't know exactly how you wanted to save the active preset ID, so I added `Config.selectedPresetID` as the active preset ID, you can find the code in the `init.lua` at `if ImGui.BeginCombo("##", UIText.Presets.Info[Config.selectedPresetID].name) then`.

I hope I was able to help you with the `Localization.lua`.

`UIText.lua` is now `en-us.lua`. There are some texts that I do not recommend translating. These are all texts that are displayed in the console for troubleshooting and support purposes. They should remain in English. I implemented this using `ConsoleText`, which simply accesses the en-us.lua directly. The `Language-Location.lua` is the new blueprint for translators.

Ps.: When I looked at the CET docs I noticed something about the font, apparently in some cases you have to make changes to the config: [Change font & language setting](https://wiki.redmodding.org/cyber-engine-tweaks/console/settings/config-file/change-font-and-font-size)

**Comment by Lonarix** [comment]
Of course I forgot to add the translated version of the preset description on the UI, sorry for the mistake.

There are probably still things that need to be optimized. If so, I'll be happy to take care of them and push them as a commit, together with a proper guide for translations later.

This way you can focus on implementing the PresetID and revising and rewriting your code.

**Comment by gramern** [comment]
Hi, the code doesn't work for me, `UIText` is reported `nil` for some reason, might be my fault, I'll look into it this weekend

**Comment by Lonarix** [comment]
Should only return nil if it wasn't loaded at all. UIText can't be used until it's been loaded at first.

```
-- init.lua

local Localization = require("Modules/Localization")
-- all texts that will be displayed outside of ui
local ConsoleText = require("Translations/en-us")
-- later I'll add ConsoleText to Localization as well

local UIText = Localization.UIText

function SetLanguage()
  Localization.GameOnScreenLang = Game.NameToString(Game.GetSettingsSystem():GetVar("/language", "OnScreen"):GetValue())
end

registerForEvent("onOverlayOpen", function()
  SetLanguage()
  Localization.translate()
  Localization.presetsUpdate()

  -- after loading enable overlay
  OverlayEnabled = true

  Calculate.CalcAspectRatio()
  Calculate.GetAspectRatio()
end)
```

UIText.lua needs to be moved and renamed `Translations/en-us.lua` in the root folder next to `init.lua`

Just to make sure, replace all `UIText` that won't be shown on UI with `ConsoleText`

If all of that doesn't work either please try replacing `Localization.GameOnScreenLang = Game.NameToString(Game.GetSettingsSystem():GetVar("/language", "OnScreen"):GetValue())` with `Localization.GameOnScreenLang = "de-de"`. I know you don't have the file de-de.lua but maybe that's where it fails.

If you did all of that then I don't know where to error comes from yet, but I'll take a look at it and fix it

**Comment by gramern** [comment]
So far I simply cloned your repo and tried to run it in the game; I put `de-de.lua` (a renamed copy of `en-us.lua`) into `Translations` folder too. It doesn't kick in with the game's language changed to German, UI stays empty, while the upvalue `UIText` is reported as `nil` in the logs when the mod tries to index it.

It's weird, because in the IDE I can access `Localization.UIText` keys, but that's all and their values are reported `unknown` afterwards. The code looks good however

**Comment by Lonarix** [comment]
That's weird. I'll take a look at it later.

Fist of I'll test it with the current release of your mod again as it worked perfectly fine there before and then with the develop-xl branch.

I'll push a fix for it as soon as I found the bug and a way to fix it.

**Comment by Lonarix** [comment]
Okay, I found the bug. I'll push it as soon as I'm done rewriting

**Comment by gramern** [comment]
The scope `local UIText = Localization.UIText` is declared at the beginning, but the `UIText` table is not updated after updating `Localization.UIText` - so it stays nil for `init.lua`. Redeclaration or assigning `Localization.UIText` after execution of `Localization.translate()` and `Localization.presetsUpdate()` helps. 

I could access `Localization.UIText` keys in the IDE as I had most of them declared in `onDraw` below. 

Regarding building nested functions: [https://stackoverflow.com/questions/6086992/lua-inner-function-vs-module-level-function. ](https://stackoverflow.com/questions/6086992/lua-inner-function-vs-module-level-function. ) In this particular context the possible performance hit is negligible, adding for the future.

Lua is fast but has its quirks. :) Please, add the fix and I'll merge.

Edit: At the same time :D

**Comment by Lonarix** [comment]
I was too lazy to google it and just rewrote everything and only then realized what the problem was. Well, I also added the IDs so that if you want to test the code, you can see straight away what it would look like.

I hope the Localization.lua will satisfy you. :')

Instead of publishing the Translation-Blueprint.lua with the normal mod, I would publish it as a simple separate file, which is already prepared with the correct path so that the translator can't make a mistake.

That should also make publishing the translation easier so that they don't accidentally publish the entire mod, you never know.

Edit: I don't know how often I've read the code and just now I found a line where I did the same with the UIText again.. fixed in last commit by now :)

**Comment by gramern** [comment]
Superb, the translation system works. :) I would fix one thing: now translated presets names don't replace the old keys in the translated `UIText` table but are added as new ones somehow, so the shown list of presets is getting longer and longer on every overlay open. Would you like to fix it now or should we merge it as it is? I can look for fix when working on 4.9.0, no problem.

Also, presets aren't applied so masking doesn't work at all, but I see no point in fixing it right now as I will change that part a bit in 4.9.0 anyway.

**Comment by Lonarix** [comment]
Why do you always get bugs? I'll take another look.

Presets are not applied? I thought I had implemented that, because when I tested it, it also saved the selected preset correctly.

Well, I'll take another look at why it keeps expanding the preset list for you, because that didn't happen for me. Did you test again by simply applying the entire commit or did you only try certain files? What I could imagine is that something isn't working properly with the IDs. I'll take another look at it today

Edit: I don't know why but somehow it didn't remember the UIText Prests on my side, I had to reinstall the mod to get the bug as well. Fixed it by simply clearing the UIText Presets before translating them

**Comment by gramern** [comment]
Squashing and merging from my PC didn't work as expected; you weren't assigned as an author of your commits. I'm squashing and merging again, this time from the website. 

I need some time to prepare for 4.9.0.

**Pull request merged**
